<a href="https://colab.research.google.com/github/TolleDennis/basic-ml-course/blob/master/03_Logistic_Regression/Solution%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework 3: Logistics Regression
Implement everywhere that has  `...`

In [88]:
import numpy as np
import pandas as pd
import sklearn.datasets

### Load dataset

In [97]:
import sklearn
from sklearn.datasets import load_iris
data = load_iris()
X, Y = data.data, data.target
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### Task 1: (1pt)
Choose only the last 2 classes (class 1 and 2) from the dataset. You may refer to the code from the lecture video.

Some numpy resource that might be useful
* Indexing in numpy: https://aman.ai/primers/numpy/#indexing
* Boolean mask: https://aman.ai/primers/numpy/#boolean-array-indexing

In [106]:
# only classify class 1 vs. class 2
# Your code here

def class1_2(X,Y):
  cond = Y < 2
  X = X[cond]
  Y = Y[cond]
  return X,Y
assert X.shape == (100, 4) #just to make sure


In [107]:
pd.DataFrame(X)

0    1    2    3
0   5.1  3.5  1.4  0.2
1   4.9  3.0  1.4  0.2
2   4.7  3.2  1.3  0.2
3   4.6  3.1  1.5  0.2
4   5.0  3.6  1.4  0.2
..  ...  ...  ...  ...
95  5.7  3.0  4.2  1.2
96  5.7  2.9  4.2  1.3
97  6.2  2.9  4.3  1.3
98  5.1  2.5  3.0  1.1
99  5.7  2.8  4.1  1.3

[100 rows x 4 columns]

### Task 2: Data normalization (1pt)
Implement z-score normalization.

Remember: normalization is done per feature, not all at once. So you need to calculate the mean and standard deviation for each feature seperately.

In [108]:
# Write your code here. 
x_means = X.mean()
x_stdevs = X.std()
X = (X - x_means) / x_stdevs


### Task 3: Construct the design matrix (1pt)
We need to add an extra column of 1 that represents the bias/intercept term


\begin{bmatrix}
1 & x_{11} & x_{12} & \dots\\
1 & x_{21} & x_{22} & \dots\\
\vdots  & \vdots &\vdots & \vdots\\
1 & x_{n1} & x_{n2} & \dots\\
\end{bmatrix}

Helpful function: https://numpy.org/doc/stable/reference/generated/numpy.hstack.html

In [109]:
# Your code here
n,m = X.shape # gives you the dimensions of your matrix
add_ones= np.ones((n,1))
X = np.hstack((add_ones,X))
print(X)

# checking the shape of X
assert X.shape == (100, 5)

[[ 1.          1.09132172  0.23778891 -0.88247291 -1.52262251]
 [ 1.          0.98463012 -0.0289401  -0.88247291 -1.52262251]
 [ 1.          0.87793851  0.0777515  -0.93581871 -1.52262251]
 [ 1.          0.82459271  0.0244057  -0.82912711 -1.52262251]
 [ 1.          1.03797592  0.29113471 -0.88247291 -1.52262251]
 [ 1.          1.25135912  0.45117211 -0.72243551 -1.41593091]
 [ 1.          0.82459271  0.18444311 -0.88247291 -1.46927671]
 [ 1.          1.03797592  0.18444311 -0.82912711 -1.52262251]
 [ 1.          0.71790111 -0.0822859  -0.88247291 -1.52262251]
 [ 1.          0.98463012  0.0244057  -0.82912711 -1.57596832]
 [ 1.          1.25135912  0.34448051 -0.82912711 -1.52262251]
 [ 1.          0.93128431  0.18444311 -0.77578131 -1.52262251]
 [ 1.          0.93128431 -0.0289401  -0.88247291 -1.57596832]
 [ 1.          0.66455531 -0.0289401  -1.04251031 -1.57596832]
 [ 1.          1.46474232  0.50451791 -0.98916451 -1.52262251]
 [ 1.          1.41139652  0.71790111 -0.82912711 -1.41

### Task 4: Model initialization (1pt)
Create parameters here. Initialize with zeros. Output should be a numpy array 

In case you forgot: $Y = \sigma(X\theta)$.

In [110]:
# Your code here
weight = np.zeros((5,))
assert weight.shape == (5, )

### Task 5: Sigmoid function (1pt)
Implement the sigmoid function. You should use `np.exp` for this


$$\sigma(z) = \frac{1}{1 + e^{-z}}$$

In [111]:
def sigmoid(z):
    # Your code here
    return 1.0 / (1.0 + np.exp(-z))
  

### Task 6: Define evaluation metrics (2pt)
Implement the accuracy score

$$\frac{\text{\# of correct prediction}}{\text{\# of datapoint}}$$

In [114]:
from sklearn.linear_model import LogisticRegression
def accuracy(X, y, weight):
    '''
    Evaluate the model, represented by `weight`, with data (X, Y).
    
    Input:
        X:      data features
        Y:      data labels
        weight: model weights
    Ouput:
        Model accuracy on input data.
        
    '''
    # implement your code here. Below are only some suggestion. 
    # You don't necessary have to follow the exact step

    #Step 1: get the model prediction

    #Step 2: Threshold the probability value to get the class. 

    #Step 3: Compare your model predicted classes with the label y

    #step 4: calculate the accuracy using the formula above
   
    datapoints = len(y)
    y_predict = sigmoid(X@weight)

    y_predict = (y_predict > 2).astype(int)
    y_correct = 0
    
    for y_value in range(len(y_predict),len(y)):
      if y_predict[y_value] == y[y_value]:
           y_correct += 1 

    accuracy_score = y_correct / datapoints 
    return accuracy_score


In [115]:
y_predict = (X@weight)
y_predict

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [116]:
accuracy(X,y,weight)

0.0

### Hyperparameters

In [69]:
#Don't change these
# learning rate
alpha = 1e-2
# epochs
epoch = 10000

### Task 7: Train the model. (3pt)
Implement the model training loop:
1. Calculate the model prediction
$$h_\theta(X) = \sigma(X\theta)$$
2. Calculate the loss/cost function 
$$ J(\theta) = \frac{-1}{m} \sum_{i=1}^{m} [y_i \ln(h_\theta(x_i)) +(1-y_i)\ln(1-h_\theta(x_i))]$$
3. Calculate the gradient
$$
\frac{\partial J(\theta)}{\partial \theta} = \frac{1}{m} X^T(Y-h_\theta(X))
$$
4. Update the model parameter 
$$\theta = \theta - \alpha \frac{\partial J(\theta)}{\partial \theta} $$
5. Calcualte the model accuracy (use the function you implemented above)

In [130]:
# your code here
for ep in range(epoch):
  y_predict = 1 / (1 + np.exp(-X @ weight))
  loss = -np.sum(Y * np.log(y_predict) + (1 - Y) * np.log(1 - y_predict)) / y_predict.size 
  m = y_predict.size
  gradient = (1 / m) * X.T @ (Y - y_predict)
  weight = weight - alpha  * gradient
    

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in multiply
  after removing the cwd from sys.path.


In [131]:
0# just to double check
assert np.allclose(weight, np.array([0.12047504, -0.44156746, -0.89309501, 2.965364, 3.3427994]))

AssertionError: ignored

In [127]:
# model accuracy
accuracy(X, Y, weight)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until


0.0

### (Optional) How low can you go?
Do anything you want to get the best performance out of the training set. For once, let's overfit to your heart's content.

In [ ]:
# do some fun code here and try to match this :)
...

In [ ]:
print('Weights:', weight)
y = 1 / (1 + np.exp(-X @ weight))
loss = -np.sum(Y * np.log(y) + (1 - Y) * np.log(1 - y)) / y.size
print('Loss:', loss)
print('Accuracy:', accuracy(X, Y, weight))

Weights: [-0.35439119 -1.62584216 -2.21192859  7.74567601  7.72844057]
Loss: 0.0594927339567942
Accuracy: 0.98
